# Dockerfile for Pipenv wrapper
# Unfortunately it seems not possible to reuse the Django Dockerfile, as not installing any packages in it
# will result in all .build-deps apks being deleted from it and pipenv failing to lock/install
# The build steps of this file are taken from the Django Dockerfile to make the build a bit faster though.

FROM python:3.8-slim

ENV PIPENV_PYUP_API_KEY=""

VOLUME /src
WORKDIR /src

# Install bash, libpq and gettext
RUN apt-get -y update && apt-get -y install bash gettext libpq-dev python-dev

# Copy Python requirements dir and Install requirements
RUN pip install -U pipenv>=2020.6.2 pip setuptools wheel
