# Generated by Django 2.2.17 on 2020-12-28 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_annotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="end",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Window end (time)",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="start",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Window start (time)",
            ),
        ),
    ]
