# Generated by Django 2.2.17 on 2021-01-01 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0003_auto_20201228_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorfile",
            name="truncation_end",
            field=models.FloatField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Truncation end (time [s])",
            ),
        ),
        migrations.AddField(
            model_name="sensorfile",
            name="truncation_start",
            field=models.FloatField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Truncation start (time [s])",
            ),
        ),
    ]
